resolver: nightly-2024-10-02

extra-deps:
  - ghc-lib-parser-9.10.1.20240511
  - ghc-lib-parser-ex-9.10.0.0
  - test-framework-0.8.2.0
  - test-framework-hunit-0.3.0.2
  - ansi-wl-pprint-0.6.9
  - ansi-terminal-1.0.2
  - ansi-terminal-types-0.11.5

save-hackage-creds: false
compiler: ghc-9.8.2
